### ISSUE TITLE
اشتباه تایپی در بخش ، جواب اما و اگر های دوچرخه سواری شهری

### ISSUE THREAD

**Issue by aminGhafoory** [jadijadi/bikezenbook#30]
این نمودار از برنامه استراوا که مسیر دوچرخه رو ثبت می‌کنه، نشون می‌ده که از ابتدای جاده لشکرک تا **رسدین** به لواسان تقریبا ۱ ساعت طول کشیده که طی اون ۴۳۷ متر ارتفاع گرفته‌ایم. اگر این مسیر رو رفته باشید می‌دانید که یکی از آن جاده‌های پیچ واپیچ و پر از شیب کوهستانی است که گذشتن از آن حتی با ماشین سخت است؛ بخصوص با پراید! اما راز رفتن در سربالایی عدم تلاش برای سریع بودن است. استفاده از دنده مناسب و آرام و مستمر رکاب زدن، تقریبا بدون خستگی و عرق کردن آدم را به مقصد خواهد رساند.

اشتباه تایپی در این قسمت 
رسیدن به اشتباه رسدین تایپ شده است
[link](http://bikezen.ir/tehran_cycling.html)

**Comment by jadijadi** [comment]
ممنون. اصلاح کردم (:
