### ISSUE TITLE
جای یه راهنمای نصب کمه

### ISSUE THREAD

**Issue by NabiKAZ** [jadijadi/bikezenbook#32]
جای یه راهنمای نصب کمه!
منتظر نظرتون نمیمونم، من خندون استارت زدم! (:

**Comment by NabiKAZ** [comment]
خب کامیت زدم.
من اینجوری نصب کردم.
حالا اگر اشتباه هست یا نیاز به اصلاح داره، دست اساتید فن رو میبوسه (:
هنوزم خندونم (:

**Comment by jadijadi** [comment]
راهنمای نصب؟ خب این یه کتابه. منطقا کسی لوکال نصبش نمی کنه که. برای نوشتن؟ نمی دونم. حالا فکر می کنم تصمیم میگیرم (: مرسی.

**Comment by NabiKAZ** [comment]
به هر حال اون کسی که میخواد توسعش بده نیاز داره که.

**Comment by jadijadi** [comment]
done. thanks.
