### ISSUE TITLE
چندین اشتباه در متن

### ISSUE THREAD

**Issue by aGoogleFan** [jadijadi/bikezenbook#9]
یک ایده خوب برای انجام این تنظیم،‌ ثابت نگه داشتن دوچرخه توسط یک نفر و تلاش شما برای رکاب زدن به جلو و عقب در وضعیتی است که تنها 
پاشنه پای شما روی زین“ قرار گرفته باشد”

دوچرخه‌ای که من برای رفت و آمد به مهمانی، محل کار و خانه دوستان استفاده می‌کنم حتما باید دارای “بارند” باشد تا بتوانم کوله‌ام را به آن ببندم. 

همچنین اگر چرخ‌های دوچرخه و میله پشتی آن “درای” شب‌نما نیست

دلیل این جیغ بودن لباس، دیده شدن بهتر سوارکار توسط راننده‌های دیگر است “از بین لباس‌های زیر، کلاه صد در صد الزامی است” و من شخصا همیشه دستکش می‌پوشم، بقیه قصه، به علاقمندی شخصی شما بستگی دارد.
 پ ن: بنظر میرسه بهتر هم میشه نوشتش، من که دو ۳ باری “لباس زیر” خوندمش. 

 در دنیا کاملا عادی است که مدیرعامل‌ها را با لباس کامل دوچرخه سواری در دفترکار ببینید یا خانمی را با کت و دامن روی دوچرخه در “مسسیر” کار.

**Comment by aGoogleFan** [comment]
بین کوتیشن آوردمشون.

**Comment by jadijadi** [comment]
ممنون اصلاحشون کردم
